name: unit_calc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  intl: ^0.18.0
  matcher: ^0.12.16
  meta: ^1.9.1
  # path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.2
  coverage: ^1.6.3
  lints: ^2.0.0
  test: ^1.21.0
