name: unit_calc
description: perform calculations with automatic unit conversion. Simple code, with 100% code coverage.
version: 2.1.0
repository: https://github.com/BentEngbers/unit-calc

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2
  matcher: ^0.12.16
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  coverage: ^1.6.3
  lints: ^4.0.0
  test: ^1.21.0
