name: PR coverage report

on:
  push:

jobs:
  mimimal-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: run tests
        run: flutter test --coverage --suppress-analytics

      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 99

  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install dart
        uses: dart-lang/setup-dart@v1

      - name: Cache pub dependencies
        id: cache-pub-dependencies
        uses: actions/cache@v3
        with:
          path: ${{env.PUB_CACHE}}
          key: ${{ runner.os }}-${{env.DART_HOME}}

      - name: analyse code
        run: dart analyze --fatal-infos

  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install dart
        uses: dart-lang/setup-dart@v1

      - name: Cache pub dependencies
        id: cache-pub-dependencies
        uses: actions/cache@v3
        with:
          path: ${{env.PUB_CACHE}}
          key: ${{ runner.os }}-${{env.DART_HOME}}
      - name: get dependencies
        run: dart pub get
      - name: REMOVE
        run: ls ${{env.PUB_CACHE}}
      - name: analyse code
        run: dart format . --set-exit-if-changed
