name: CI analyse & format

on:
  push:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install dart
        uses: dart-lang/setup-dart@v1
      - name: Cache pub dependencies
        id: cache-pub-dependencies
        uses: actions/cache@v3
        with:
          path: ${{env.PUB_CACHE}}
          key: ${{ runner.os }}-${{env.DART_HOME}}
      - name: get dependencies
        run: dart pub get

      - name: analyse code
        run: dart analyze --fatal-infos

  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install dart
        uses: dart-lang/setup-dart@v1

      - name: analyse code
        run: dart format . --set-exit-if-changed
