name: PR coverage report

on:
  push:

jobs:
  mimimal-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: run tests
        run: flutter test --coverage --suppress-analytics
        
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 99

  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install dart
        uses: dart-lang/setup-dart@v1

      - name: analyse code
        run: dart analyze --fatal-infos

  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install dart
        uses: dart-lang/setup-dart@v1

      - name: analyse code
        run: dart format . --set-exit-if-changed

