name: test & coverage

on: 
    pull_request:

jobs: 
    test:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
          contents: write
        steps: 
            
            - name: checkout repo 
              uses: actions/checkout@v3
            
            - name: install flutter 
              uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  cache: true
            - name: run tests
              run: flutter test --coverage --suppress-analytics

              
            - name: check coverage
              uses: romeovs/lcov-reporter-action@v0.3.1
              with:
                github-token: ${{ github.token }}
                lcov-file: ./coverage/lcov.info