name: test & coverage

on: 
    push:


jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            
            - name: checkout repo 
              uses: actions/checkout@v3
            
            - name: install flutter 
              uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  cache: true
            - name: run tests
              run: flutter test --coverage --enable-telemetry
              
            - name: check coverage
              uses: romeovs/lcov-reporter-action@v0.2.16
              with:
                github-token: ${{ github.token }}
                lcov-file: ./coverage/lcov.info